export default {
    content: ['./index.html', './src/**/*.{html,js,vue}'],
    safelist: [
        'text-error',
        'text-warning',
        'text-neutral',
        'text-info',
        'text-success',
        'text-primary',
        'progress-error',
        'progress-warning',
        'progress-neutral',
        'progress-info',
        'progress-success',
        'progress-primary',
        'badge-error',
        'badge-warning',
        'badge-neutral',
        'badge-info',
        'badge-success',
        'badge-primary',
    ],
}
